apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${PROJECT_NAME}
  labels:
    app.kubernetes.io/name: ${PROJECT_NAME}
    app.kubernetes.io/component: api-server
    app.kubernetes.io/instance: ${PROJECT_NAME}-api-server
    app.kubernetes.io/version: ${PROJECT_VERION}
    app.kubernetes.io/part-of: ${PROJECT_NAME}
    # app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ${PROJECT_NAME}
      app.kubernetes.io/component: api-server
      app.kubernetes.io/instance: ${PROJECT_NAME}-api-server
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ${PROJECT_NAME}
        app.kubernetes.io/component: api-server
        app.kubernetes.io/instance: ${PROJECT_NAME}-api-server
    spec:
      containers:
        - name: api-server
          image: $IMG:$PROJECT_VERION
          ports:
            - containerPort: ${HTTP_PORT}
          env:
            - name: LOG_LEVEL
              value: "${LOG_LEVEL}"
            - name: HTTP_PORT
              value: "${HTTP_PORT}"
            - name: HTTP_READINESS_PROBE_PERIOD_SECONDS
              value: "${HTTP_READINESS_PROBE_PERIOD_SECONDS}"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /healthz
              port: ${HTTP_PORT}
            periodSeconds: ${HTTP_READINESS_PROBE_PERIOD_SECONDS}
